[package]
name = "{{project-name}}"
version = "0.0.1"
edition = "2021"
authors = ["{{authors}}"]
description = ""

repository = "https://github.com/{{github_user}}/{{project-name}}"
license = "MIT"

[dependencies]
